title:        {"API Evangelist"}
url:          http://apievangelist.com
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
